### ISSUE TITLE
Asking about quantitative metric

### ISSUE THREAD

**Issue by bqm1111** [JiangXinni/D2A2#1]
Thanks for your exciting work.

I have a question regarding how you evaluate the performance of your method. What is the ground truth of your method? For example in NYUv2 dataset,  what is the x4, x8, x16 groundtruth?

**Comment by JiangXinni** [comment]
The original depth map in the dataset is the ground truth. In the experiment, we used bicubic to downsample the original depth map as LR.

**Comment by bqm1111** [comment]
Thanks for the answer.
